### ISSUE TITLE
how to handle db version upgrades?

### ISSUE THREAD

**Issue by axelav** [lrlna/nanoidb#1]
this is a nice wrapper around IDB, though I can't see how version upgrades should be handled. I've seen examples where the `oldVersion` prop on the `onupgradeneeded` event is used to decide which 'migrations' are needed. something like:

```
open.onupgradeneeded = function (e) {
  var db = open.result;
  if (e.oldVersion < 1) {
    // create v1 schema
  }
  if (e.oldVersion < 2) {
    // upgrade v1 to v2 schema
  }
  if (e.oldVersion < 3) {
    // upgrade v2 to v3 schema
  }
  // ...
}
```

but without having that property available, I can't see how to do this properly. thoughts?

**Comment by axelav** [comment]
https://github.com/lrlna/nanoidb/pull/2

**Comment by lrlna** [comment]
Saw you pull request! This is a good catch, thanks :D totally viable to pass the event back as well to handle schema diffs.
